### ISSUE TITLE
Criar end points Web Service

### ISSUE THREAD

**Issue by isabelleoliveira9** [Gileno29/COVID-SYS#18]
Sugerido por: Prof. Lucas Vieira
Para que existe: Para disponibilizar dados via Json para desenvolvedores que irão consumir os dados da API desenvolvida.

**Comment by Gileno29** [comment]
Criei end point que disponibiliza todos os dados de uma única vez, faltam os outros end Points

**Comment by Gileno29** [comment]
Correção o end point adicionado foi o de buscar por id.
